---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team1
  namespace: team1
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: team1
  sourceRef:
    kind: GitRepository
    name: team1