---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: team1
  namespace: team1
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/la-cc/simple-webapp-green.git