apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: default
spec:
  encryptedData:
    my-secret: AgAJrb7LFvUFss3O/FeQ2XF0y7zSrAwMOrQyM8J9DLMhiH4fXAs5lhQFN2s/jim+BKDIFrgNo1A9c6nWXDDaEpkUFz8ZqO/tmmaSMrOL88kmlnWpRw7PGtzv3HhTLhDimYNGi+M6EwRXLp+OYjY5LZXtO4jqABTOM+URCGm8aENy97NrJBMWD3+w1RAYA8lSjsrw6mklxTOqpNwd7w4UjPnxM/t8OPtdN/P1G4wswgvZdJDMOamGBX23lHvCUxsqEktzXjdISJkyPvAwnUs1E2sXquHx7ZVRTA6CTnjwa4MyPnJunO/xHGkqDK0eZKbY6wpeD84YWXhCSVtRdjtnZRBak2TsklfBb5QhMV9gnnUd81zEUn9i3fa2TWxVkLiA1Ux8HuJaTEyYqIydre8V1SMqjrFQ0e65XuDfSWFw3Qr489g3gm2Wzeg8iYeAHHlaNjQLaIJL8heQRMGFwDKPompYm/Ro78J+Mq8ovu2d4chPl6my0Fk2oLXKUKOFCwjuWkgRbd8lUnZP4YTyvgGLHKUoLlzWBHx44LqpAv8gI0CknPpllQxAvtc8CjYMYUw25NrfdMdY4QlrP8x9oCfJ2IQq7Hv9g5WYG9wl2zaUDDpt58X2XLSW7btIlv4PyktEZRVzqAq0MBjAKuZfn1cukQcrNKS9jPPwUANAfHTGrJ2CFTwz+bwD042bTuRuBUg5xsUDC84NNQ==
  template:
    metadata:
      name: mysecret
      namespace: default

